# Generated by Django 5.2.15 on 2026-06-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hisobotlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelQator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qator_data', models.JSONField()),
                ('jadval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hisobotlar.exceljadval')),
            ],
        ),
    ]
