# Generated by Django 5.2.15 on 2026-06-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelJadval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fayl', models.FileField(upload_to='excel_fayllar/')),
                ('yuklangan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('ustunlar', models.JSONField(default=list)),
                ('yuklagan_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PDFHisobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fayl', models.FileField(upload_to='pdf_fayllar/')),
                ('yuklangan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('holat', models.CharField(default='kutilmoqda', max_length=20)),
                ('yuklagan_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImtihonNatija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_nomi', models.CharField(max_length=200)),
                ('fan_oqituvchi', models.CharField(max_length=200)),
                ('guruh', models.CharField(max_length=100)),
                ('jami_talabalar', models.IntegerField(default=0)),
                ('baho_5', models.IntegerField(default=0)),
                ('baho_4', models.IntegerField(default=0)),
                ('baho_3', models.IntegerField(default=0)),
                ('kelmadi', models.IntegerField(default=0)),
                ('hisobot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hisobotlar.pdfhisobot')),
            ],
        ),
    ]
