# Generated by Django 6.0.6 on 2026-06-11 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hisobotlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalabaYozuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guruh', models.CharField(db_index=True, max_length=100)),
                ('fan_nomi', models.CharField(db_index=True, max_length=200)),
                ('fan_oqituvchi', models.CharField(db_index=True, max_length=200)),
                ('fio', models.CharField(max_length=300)),
                ('reyting_raqam', models.CharField(blank=True, max_length=20)),
                ('joriy', models.IntegerField(default=0)),
                ('oraliq', models.IntegerField(default=0)),
                ('joriy_oraliq', models.IntegerField(default=0)),
                ('yakuniy', models.IntegerField(default=0)),
                ('ozlashtirish', models.IntegerField(default=0)),
                ('baho', models.IntegerField(default=0)),
                ('natija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talabalar', to='hisobotlar.imtihonnatija')),
            ],
            options={
                'ordering': ['guruh', 'fio'],
                'indexes': [models.Index(fields=['guruh', 'fan_nomi'], name='hisobotlar__guruh_6444e6_idx'), models.Index(fields=['fan_oqituvchi'], name='hisobotlar__fan_oqi_2c8d79_idx')],
            },
        ),
    ]